### ISSUE TITLE
api now reporting empty string values for the field "disease_status"

### ISSUE THREAD

**Issue by aahunter** [muccg/bpa-metadata#53] opened 2016-09-12 01:57 UTC
Reported by Shilo Banihit:

It seems like the API endpoint at https://downloads.bioplatforms.com/antibiotic_resistant_pathogens/api/v2/sepsis_samples/

and 

https://downloads.bioplatforms.com/antibiotic_resistant_pathogens/api/v2/hosts/

are now reporting empty string values for the field "disease_status", whereas previously it had non-empty values.

Can you please check?

Thanks.

**Comment by grahame** [comment] 2016-09-12 03:57
Dupe of #56

**Comment by grahame** [comment] 2016-09-13 07:37
Not really a dupe - my mistake

**Comment by sztamas** [comment] 2016-09-13 13:18
Similarly as in #56, we believe this is because BPA Project Managers are editing that data.
Looking at the septic sample data in the admin interface there is no data in the Disease Status column at all.

**Comment by grahame** [comment] 2016-11-25 07:27
This behaviour has been discussed with RDS, and we now have consistent behaviour in the v3 API.

**Closed by grahame** 2016-11-25 07:27 UTC
Labels: wontfix
