### ISSUE TITLE
Mi Seq Track List now empty

### ISSUE THREAD

**Issue by shilob** [muccg/bpa-metadata#56] opened 2016-09-12 03:53 UTC
MiSeq API endpoint used to have data, now returning empty list:

https://downloads.bioplatforms.com/antibiotic_resistant_pathogens/api/v2/track_miseq/

Thanks in advance for looking into this.

**Comment by sztamas** [comment] 2016-09-13 08:33
We believe this is because BPA Project Managers were editing that data.
The data was probably deleted when you tried to access it.
If you access the API endpoint now it does have data, so we can't reproduce the problem.

**Comment by grahame** [comment] 2016-09-15 03:10
Closing as believe this to be resolved, @shilob please re-open if necessar.

**Closed by grahame** 2016-09-15 03:10 UTC
Labels: question, wontfix
